# 🛡️ Phishing Detection Test 
End-to-end: ingest `.eml` files

In [1]:
from phishing_engine import analyze_email, load_email
import pandas as pd

## 1. Analyse a single email

In [2]:
email = load_email("sample/sample-21.eml")
res = analyze_email(email, enable_whois=True)
print(res.report())

 PHISHING TRIAGE REPORT
================================================================
 From    : Ariana <newsmail@app9l.serenitepure.fr>
 Subject : Het begint weer warm te worden
================================================================
 RISK SCORE :  12.10/100  [███░░░░░░░░░░░░░░░░░░░░░░]
 VERDICT    : suspicious
 ACTION     : FLAG
================================================================
 CHECK BREAKDOWN:
  [·] 1. Domain age                          risk  10  (wt   0.7)
        - serenitepure.fr registered 1748 days ago (2021-09-08).
  [ ] 2. Typosquatting                       risk   0  (wt   0.0)
  [ ] 3. Urgency and Credential harvesting   risk   0  (wt   0.0)
  [ ] 4. URL with IP address                 risk   0  (wt   0.0)
  [·] 5. BEC patterns                        risk  15  (wt  1.65)
        - Reply-To diverts responses off-domain (common in BEC).
  [✗] 6. From and Reply-To domain mismatch   risk  65  (wt  9.75)
        - Reply-To domain (aichakandisha.com) differs from From (serenitepure.fr).
        - Return-Path domain (arnhemophthalmics.com) differs from From (serenitepure.fr).
  [ ] 7. Dangerous attachments               risk   0  (wt   0.0)
  [ ] 8. Display-name spoofing               risk   0  (wt   0.0)
  [ ] 9. Generic greeting                    risk   0  (wt   0.0)
  [ ] 10. Link text vs actual URL            risk   0  (wt   0.0)
================================================================
 RECOMMENDATIONS:
  • Replies leave the sender's stated domain — treat as suspicious.
================================================================

In [3]:
df = pd.DataFrame(res.rows())
df[['check_name','check_risk', 'check_severity', 'check_weighted', 'check_evidence']]

,check_name,check_risk,check_severity,check_weighted,check_evidence
0,1. Domain age,10,low,0.70,[serenitepure.fr registered 1748 days ago (202...
1,2. Typosquatting,0,none,0.00,[]
2,3. Urgency and Credential harvesting,0,none,0.00,[]
3,4. URL with IP address,0,none,0.00,[]
4,5. BEC patterns,15,low,1.65,[Reply-To diverts responses off-domain (common...
5,6. From and Reply-To domain mismatch,65,high,9.75,[Reply-To domain (aichakandisha.com) differs f...
6,7. Dangerous attachments,0,none,0.00,[]
7,8. Display-name spoofing,0,none,0.00,[]
8,9. Generic greeting,0,none,0.00,[]
9,10. Link text vs actual URL,0,none,0.00,[]

In [4]:
df

,from,subject,overall_risk,classification,action,recommendations,check_name,check_risk,check_severity,check_weighted,check_evidence
0,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,1. Domain age,10,low,0.70,[serenitepure.fr registered 1748 days ago (202...
1,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,2. Typosquatting,0,none,0.00,[]
2,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,3. Urgency and Credential harvesting,0,none,0.00,[]
3,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,4. URL with IP address,0,none,0.00,[]
4,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,5. BEC patterns,15,low,1.65,[Reply-To diverts responses off-domain (common...
5,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,6. From and Reply-To domain mismatch,65,high,9.75,[Reply-To domain (aichakandisha.com) differs f...
6,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,7. Dangerous attachments,0,none,0.00,[]
7,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,8. Display-name spoofing,0,none,0.00,[]
8,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,9. Generic greeting,0,none,0.00,[]
9,newsmail@app9l.serenitepure.fr,Het begint weer warm te worden,12.1,suspicious,FLAG,[Replies leave the sender's stated domain — tr...,10. Link text vs actual URL,0,none,0.00,[]